#ifndef PROFILE_CONSTANTS_H
#define PROFILE_CONSTANTS_H

#define DEFAULT_ITERATIONS 100000
#define DEFAULT_DELAY_IN_MILLISECONDS 0
#define DEFAULT_NUMBER_OF_DEVICES 0
#define DEFAULT_LIMIT 0
#define DEFAULT_INCLUDE_ITERATION_RUNTIME_IN_DELAY false
#define DEFAULT_VERBOSE false
#define DEFAULT_PATTERN NULL
#define DEFAULT_METRICS NULL

#endif
